import Main
open Main
namespace GeneratedRules

def generatedRuleset : List ComplianceRule := [
{ id := "ICDR_4_22",
    title := "Exemption for Securities under clause (b), (d) and (e) of sub-regulation (1) of regulation 9 of SAST Regulations, 2011",
    reference := "ICDR_4_22",
    check := fun i => True, -- No applicable fields in Issuer structure
    failReason := fun _ => "This rule does not apply to the provided Issuer structure.",
    remedy? := none },
  { id := "ICDR_5_1_a",
    title := "Disqualification: issuer/promoters/directors/selling shareholders debarred",
    reference := "ICDR_5_1_a",
    check := fun i => (i.is_debarred) || (i.has_debarred_directors) || (i.selling_shareholders_debarred),
    failReason := fun i => if (i.is_debarred) then "Issuer is debarred." else if (i.has_debarred_directors) then "One or more directors are debarred." else if (i.selling_shareholders_debarred) then "Selling shareholders are debarred." else "No disqualifying debarment found.",
    remedy? := some "Lift the debarment to become eligible." },
  { id := "ICDR_5_1_b",
    title := "Disqualification: promoter/director of another debarred company",
    reference := "ICDR_5_1_b",
    check := fun i => (i.directors.exists (fun d => d.other_debarred_companies.length > 0)),
    failReason := fun i => if (i.directors.exists (fun d => d.other_debarred_companies.length > 0)) then "One or more directors are associated with a debarred company." else "No disqualifying director-company relationship found.",
    remedy? := some "Remove the association with the debarred company to become eligible." },
  { id := "ICDR_5_1_c",
    title := "Disqualification: wilful defaulter or fraudulent borrower",
    reference := "ICDR_5_1_c",
    check := fun i => (i.is_fraudulent),
    failReason := fun _ => "Issuer is fraudulent.",
    remedy? := some "Rectify the fraudulent activities to become eligible." },
  { id := "ICDR_5_2",
    title := "No outstanding convertibles/rights (pre-IPO)",
    reference := "ICDR_5_2",
    check := fun i => !i.has_outstanding_convertibles,
    failReason := fun _ => "Issuer has outstanding convertibles.",
    remedy? := some "Resolve the outstanding convertibles to become eligible." },
  { id := "ICDR_6_1_a",
    title := "Net tangible assets ≥ ₹3 cr (pre-IPO)",
    reference := "ICDR_6_1_a",
    check := fun i => (i.net_tangible_assets.length == 3) && allGeNat i.net_tangible_assets 30000000,
    failReason := fun i =>
      let ntaMsg :=
        if !(lengthIs i.net_tangible_assets 3) then "Need 3 full-year NTA figures."
        else if !(allGeNat i.net_tangible_assets 30000000) then "Each year’s net tangible assets must be ≥ ₹3.0 crore."
        else ""
      String.intercalate " " ([ntaMsg].filter (· ≠ "")),
    remedy? := some "Demonstrate ≥ ₹3 cr in each of the last 3 full years." },
  { id := "ICDR_6_1_b",
    title := "Operating profit ≥ ₹15 cr (pre-IPO)",
    reference := "ICDR_6_1_b",
    check := fun i => (lengthIs i.operating_profits 3) && allGeNat i.operating_profits 150000000,
    failReason := fun i =>
      let fails := i.operating_profits.zipIdx |>.filter (fun (x, idx) => x < 150000000)
      let years := fails.map (fun (_, idx) => s!"Year {idx + 1}")
      "Operating profit below ₹15 cr in: " ++ String.intercalate ", " years,
    remedy? := some "Demonstrate ≥ ₹15 cr operating profit in each of the last 3 full financial years (restated, consolidated)." },
  { id := "ICDR_6_1_c",
    title := "Net worth ≥ ₹1 cr (pre-IPO)",
    reference := "ICDR_6_1_c",
    check := fun i => (lengthIs i.net_worths 3) && allGeNat i.net_worths 10000000,
    failReason := fun i =>
      let fails := i.net_worths.zipIdx |>.filter (fun (x, idx) => x < 10000000)
      let years := fails.map (fun (_, idx) => s!"Year {idx + 1}")
      "Net worth below ₹1 cr in: " ++ String.intercalate ", " years,
    remedy? := some "Increase equity/retained earnings to meet ≥ ₹1 cr in each of the last 3 full years." },
  { id := "ICDR_7_1_a",
    title := "Application for in-principle approval to one or more stock exchanges",
    reference := "Regulation 7(1)(a)",
    check := fun i => i.applied_to_stock_exchange,
    failReason := fun _ => "No application for in-principle approval submitted.",
    remedy? := some "Apply to one or more stock exchanges for in-principle approval." },
  { id := "ICDR_7_1_b",
    title := "Agreement with depository for dematerialisation of securities",
    reference := "Regulation 7(1)(b)",
    check := fun i => i.has_demat_agreement,
    failReason := fun _ => "No agreement with a depository for dematerialisation.",
    remedy? := some "Sign an agreement with a depository for dematerialisation." },
  { id := "ICDR_7_1_c",
    title := "All specified securities held by promoters in dematerialized form",
    reference := "7(1)(c)",
    check := fun i => i.promoter_securities_demat,
    failReason := fun _ => "Promoters' specified securities not in dematerialised form.",
    remedy? := some "Convert promoters' specified securities to dematerialised form." },
  { id := "ICDR_7_1_d",
    title := "All existing partly paid-up equity shares fully paid or forfeited",
    reference := "7(1)(d)",
    check := fun i => i.no_partly_paid_shares,
    failReason := fun _ => "Existing partly paid-up equity shares not fully paid or forfeited.",
    remedy? := some "Fully pay or forfeit existing partly paid-up equity shares." },
  { id := "ICDR_7_1_e",
    title := "Firm arrangements of finance towards 75% of issue proceeds",
    reference := "7(1)(e)",
    check := fun i => i.finance_75_percent_done,
    failReason := fun _ => "No firm arrangements of finance towards 75% of issue proceeds.",
    remedy? := some "Secure firm arrangements of finance towards 75% of issue proceeds." },
  { id := "ICDR_8_core",
    title := "Equity shares offered for sale must be held for at least 1 year",
    reference := "ICDR_8_core",
    check := fun i => (i.has_held_equity_shares_for_1_year),
    failReason := fun _ => "Equity shares offered for sale not held for at least 1 year.",
    remedy? := some "Hold equity shares for at least 1 year before offering them for sale." },
  { id := "ICDR_8_provided",
    title := "Equity shares from conversion/exchange of compulsorily convertible securities also subject to holding period",
    reference := "ICDR_8_provided",
    check := fun i => True, -- No applicable fields in Issuer structure
    failReason := fun _ => "This rule does not apply to the provided Issuer structure.",
    remedy? := none },
  { id := "ICDR_8_provided_further",
    title := "Holding period of 1 year must be complied at the time of filing draft offer document",
    reference := "ICDR_8_provided_further",
    check := fun i => True, -- No applicable fields in Issuer structure
    failReason := fun _ => "This rule does not apply to the provided Issuer structure.",
    remedy? := none },
  { id := "ICDR_8_a",
    title := "Exemption for offer for sale of government companies or statutory authorities",
    reference := "ICDR_8_a",
    check := fun i => True, -- No applicable fields in Issuer structure
    failReason := fun _ => "This rule does not apply to the provided Issuer structure.",
    remedy? := none },
  { id := "ICDR_8_b",
    title := "Exemption for equity shares acquired under court-approved schemes or government approval",
    reference := "ICDR_8_b",
    check := fun i => True, -- No applicable fields in Issuer structure
    failReason := fun _ => "This rule does not apply to the provided Issuer structure.",
    remedy? := none },
  { id := "ICDR_8_c",
    title := "Exemption for equity shares issued under bonus issue on securities held for at least 1 year",
    reference := "ICDR_8_c",
    check := fun i => True, -- No applicable fields in Issuer structure
    failReason := fun _ => "This rule does not apply to the provided Issuer structure.",
    remedy? := none },
  { id := "ICDR_9",
    title := "IPO of convertible debt instruments without equity listing",
    reference := "ICDR_9",
    check := fun i => True, -- No applicable fields in Issuer structure
    failReason := fun _ => "This rule does not apply to the provided Issuer structure.",
    remedy? := none },
  { id := "ICDR_10",
    title := "Additional requirements for issue of convertible debt instruments",
    reference := "ICDR_10",
    check := fun i => True, -- No applicable fields in Issuer structure
    failReason := fun _ => "This rule does not apply to the provided Issuer structure.",
    remedy? := none },
  { id := "ICDR_10_1b",
    title := "Debenture trustee for IPO of convertible debt instruments",
    reference := "ICDR_10_1b",
    check := fun i => True, -- No applicable fields in Issuer structure
    failReason := fun _ => "This rule does not apply to the provided Issuer structure.",
    remedy? := none },
  { id := "ICDR_13_1a",
    title := "Tenure of warrants ≤ 18 months",
    reference := "13(1)(a)",
    check := fun i => (i.warrant_tenure <= 18),
    failReason := fun _ => "Warrant tenure exceeds 18 months.",
    remedy? := some "Reduce warrant tenure to ≤ 18 months." },
  { id := "ICDR_13_1c",
    title := "Upfront determination of exercise price",
    reference := "13(1)(c)",
    check := fun i => (i.upfront_exercise_price),
    failReason := fun _ => "Exercise price not determined upfront.",
    remedy? := some "Determine the exercise price upfront and receive at least 25% of the consideration amount based on the exercise price upfront." },
  { id := "ICDR_14_1",
    title := "Minimum promoters’ contribution ≥ 20%",
    reference := "14(1)",
    check := fun i => (i.promoter_contribution >= 20),
    failReason := fun _ => "Promoters' contribution is less than 20%.",
    remedy? := some "Increase promoters’ contribution to meet the minimum of 20%." },
  { id := "ICDR_13_1d",
    title := "Warrant consideration forfeiture",
    reference := "Regulation 13(1)(d)",
    check := fun i => True, -- No applicable fields in Issuer structure
    failReason := fun _ => "This rule does not apply to the provided Issuer structure.",
    remedy? := none },
  { id := "ICDR_15_15_a_i",
    title := "Ineligible securities: non-cash acquisition or revaluation/capitalization",
    reference := "15(1)(a)(i)",
    check := fun i => True, -- No applicable fields in Issuer structure
    failReason := fun _ => "This rule does not apply to the provided Issuer structure.",
    remedy? := none },
  { id := "ICDR_15_15_a_ii",
    title := "Ineligible securities: bonus issue against ineligible shares",
    reference := "15(1)(a)(ii)",
    check := fun i => True, -- No applicable fields in Issuer structure
    failReason := fun _ => "This rule does not apply to the provided Issuer structure.",
    remedy? := none },
  { id := "ICDR_15_1",
    title := "Specified securities ineligible for minimum promoters’ contribution (preceding three years, consideration other than cash)",
    reference := "ICDR_15_1",
    check := fun i => True, -- No applicable fields in Issuer structure
    failReason := fun _ => "This rule does not apply to the provided Issuer structure.",
    remedy? := none },
  { id := "ICDR_15_1_i",
    title := "Specified securities ineligible for minimum promoters’ contribution (preceding three years, bonus issue)",
    reference := "ICDR_15_1_i",
    check := fun i => True, -- No applicable fields in Issuer structure
    failReason := fun _ => "This rule does not apply to the provided Issuer structure.",
    remedy? := none },
  { id := "ICDR_16_1a",
    title := "Lock-in of specified securities held by promoters (minimum contribution)",
    reference := "Regulation 16(1)(a)",
    check := fun i => (i.lock_in_period_minimum_contribution == 18),
    failReason := fun _ => "Lock-in period for minimum promoters’ contribution is not 18 months.",
    remedy? := some "Extend the lock-in period for minimum promoters’ contribution to 18 months." },
  { id := "ICDR_16_1b",
    title := "Lock-in of specified securities held by promoters (excess contribution)",
    reference := "Regulation 16(1)(b)",
    check := fun i => (i.lock_in_period_excess_contribution == 6),
    failReason := fun _ => "Lock-in period for promoters’ excess contribution is not 6 months.",
    remedy? := some "Extend the lock-in period for promoters’ excess contribution to 6 months." },
  { id := "ICDR_17_c",
    title := "Lock-in of specified securities held by persons other than promoters",
    reference := "ICDR_17_c",
    check := fun i => (i.lock_in_period == 6) && (i.lock_in_holders == "persons other than promoters"),
    failReason := fun _ => "Lock-in period or holders are incorrect for specified securities held by persons other than promoters.",
    remedy? := some "Correct the lock-in period and holders for specified securities held by persons other than promoters." },
  { id := "ICDR_17_c_i",
    title := "Lock-in of convertible securities and resultant equity shares",
    reference := "ICDR_17_c_i",
    check := fun i => True, -- No applicable fields in Issuer structure
    failReason := fun _ => "This rule does not apply to the provided Issuer structure.",
    remedy? := none },
  { id := "ICDR_17_c_ii",
    title := "Lock-in of bonus equity shares",
    reference := "ICDR_17_c_ii",
    check := fun i => True, -- No applicable fields in Issuer structure
    failReason := fun _ => "This rule does not apply to the provided Issuer structure.",
    remedy? := none },
  { id := "ICDR_22",
    title := "Lock-in of specified securities",
    reference := "ICDR_22",
    check := fun i => True, -- No applicable fields in Issuer structure
    failReason := fun _ => "This rule does not apply to the provided Issuer structure.",
    remedy? := none },
  { id := "ICDR_23",
    title := "Appointment of lead manager(s)",
    reference := "ICDR_23",
    check := fun i => (i.lead_manager_appointment),
    failReason := fun _ => "No lead manager(s) appointed.",
    remedy? := some "Appoint one or more merchant bankers, which are registered with the Board, as lead manager(s) to the issue." },
  { id := "ICDR_23_1",
    title := "Rights, obligations and responsibilities of lead managers",
    reference := "ICDR_23_1",
    check := fun i => True, -- No applicable fields in Issuer structure
    failReason := fun _ => "This rule does not apply to the provided Issuer structure.",
    remedy? := none }
]

def issuerQuestionsChunk : List (String × String × String) := [
  ("is_debarred", "Is the issuer debarred?", "Bool"),
  ("has_debarred_directors", "Do any directors have a debarment record?", "Bool"),
  ("selling_shareholders_debarred", "Are selling shareholders debarred?", "Bool"),
  ("directors.*.other_debarred_companies", "Which companies are the directors associated with (if any)?", "List Nat"),
  ("has_outstanding_convertibles", "Does the issuer have outstanding convertibles or rights to receive equity before filing?", "Bool"),
  ("net_tangible_assets", "What is the net tangible assets for each of the last 3 full years (₹ paise)?", "List Nat"),
  ("monetary_asset_ratio", "What percentage of net tangible assets are held in monetary assets?", "Nat"),
  ("used_monetary_assets", "Have excess monetary assets been used or firmly committed?", "Bool"),
  ("is_offer_for_sale_only", "Is the IPO entirely an offer for sale (no fresh issue)?", "Bool"),
  ("operating_profits", "What is the operating profit for each of the last 3 full years (₹ paise)?", "List Nat"),
  ("net_worths", "What is the net worth for each of the last 3 full years (₹ paise)?", "List Nat"),
  ("changed_name_recently", "Has the company changed its name within the last 1 year?", "Bool"),
  ("percent_revenue_from_new_name", "What percentage of revenue came from the new-name activity in the preceding full year?", "Nat"),
  ("applied_to_stock_exchange", "Has an application been made to one or more stock exchanges for in-principle approval?", "Bool"),
  ("has_demat_agreement", "Is there an agreement with a depository for dematerialisation of securities?", "Bool"),
  ("promoter_securities_demat", "Are all specified securities held by promoters in dematerialised form?", "Bool"),
  ("no_partly_paid_shares", "Have all existing partly paid-up equity shares been fully paid or forfeited?", "Bool"),
  ("finance_75_percent_done", "Have firm arrangements of finance towards 75% of issue proceeds been made?", "Bool"),
  ("warrant_tenure", "What is the tenure of warrants (months)?", "Nat"),
  ("upfront_exercise_price", "Is the exercise price determined upfront and at least 25% of the consideration amount based on the exercise price received upfront?", "Bool"),
  ("promoter_contribution", "What percentage of post-issue capital is held by promoters?", "Nat"),
  ("lock_in_period_minimum_contribution", "What is the lock-in period for minimum promoters’ contribution (months)?", "Nat"),
  ("lock_in_period_excess_contribution", "What is the lock-in period for promoters’ excess contribution (months)?", "Nat"),
  ("lock_in_period", "What is the lock-in period for specified securities held by persons other than promoters (months)?", "Nat"),
  ("lock_in_holders", "Who holds the specified securities (persons other than promoters)?", "String")
]

def issuerQuestions : List (String × String × String) := [
("is_debarred", "Is the issuer debarred?", "Bool"),
  ("has_debarred_directors", "Do any directors have a debarment record?", "Bool"),
  ("selling_shareholders_debarred", "Are selling shareholders debarred?", "Bool"),
  ("directors.*.other_debarred_companies", "Which companies are the directors associated with (if any)?", "List Nat"),
  ("has_outstanding_convertibles", "Does the issuer have outstanding convertibles or rights to receive equity before filing?", "Bool"),
  ("net_tangible_assets", "What is the net tangible assets for each of the last 3 full years (₹ paise)?", "List Nat"),
  ("monetary_asset_ratio", "What percentage of net tangible assets are held in monetary assets?", "Nat"),
  ("used_monetary_assets", "Have excess monetary assets been used or firmly committed?", "Bool"),
  ("is_offer_for_sale_only", "Is the IPO entirely an offer for sale (no fresh issue)?", "Bool"),
  ("operating_profits", "What is the operating profit for each of the last 3 full years (₹ paise)?", "List Nat"),
  ("net_worths", "What is the net worth for each of the last 3 full years (₹ paise)?", "List Nat"),
  ("changed_name_recently", "Has the company changed its name within the last 1 year?", "Bool"),
  ("percent_revenue_from_new_name", "What percentage of revenue came from the new-name activity in the preceding full year?", "Nat"),
  ("applied_to_stock_exchange", "Has an application been made to one or more stock exchanges for in-principle approval?", "Bool"),
  ("has_demat_agreement", "Is there an agreement with a depository for dematerialisation of securities?", "Bool"),
  ("promoter_securities_demat", "Are all specified securities held by promoters in dematerialised form?", "Bool"),
  ("no_partly_paid_shares", "Have all existing partly paid-up equity shares been fully paid or forfeited?", "Bool"),
  ("finance_75_percent_done", "Have firm arrangements of finance towards 75% of issue proceeds been made?", "Bool"),
  ("warrant_tenure", "What is the tenure of warrants (months)?", "Nat"),
  ("upfront_exercise_price", "Is the exercise price determined upfront and at least 25% of the consideration amount based on the exercise price received upfront?", "Bool"),
  ("promoter_contribution", "What percentage of post-issue capital is held by promoters?", "Nat"),
  ("lock_in_period_minimum_contribution", "What is the lock-in period for minimum promoters’ contribution (months)?", "Nat"),
  ("lock_in_period_excess_contribution", "What is the lock-in period for promoters’ excess contribution (months)?", "Nat"),
  ("lock_in_period", "What is the lock-in period for specified securities held by persons other than promoters (months)?", "Nat"),
  ("lock_in_holders", "Who holds the specified securities (persons other than promoters)?", "String")
]

end GeneratedRules
