import Main
open Main
namespace GeneratedRules

def generatedRuleset : List ComplianceRule := [
{ id := "ICDR_6_1_a", title := "Net tangible assets ≥ ₹3 cr, with limit on monetary assets", reference := "6(1)(a)", check := fun i => (i.net_tangible_assets.length == 3) && i.net_tangible_assets.all (fun x => x >= 30000000) && (i.monetary_asset_ratio < 50), failReason := fun i => if (i.net_tangible_assets.length != 3) then "Need 3 full-year net tangible assets figures." else if (i.monetary_asset_ratio >= 50) then "Monetary assets exceed 50% of net tangible assets.", remedy? := some "Ensure net tangible assets are greater than ₹3 cr, calculated on restated and consolidated basis, in each of the preceding three full years (of twelve months each), with monetary assets not exceeding 50%." },
  { id := "ICDR_6_1_b", title := "Operating profit ≥ ₹15 cr in each of last 3 years", reference := "6(1)(b)", check := fun i => (i.operating_profits.length == 3) && i.operating_profits.all (fun x => x >= 150000000), failReason := fun i => if (i.operating_profits.length != 3) then "Need 3 full-year operating profit figures." else "Operating profit below ₹15 cr in one or more of the preceding three years.", remedy? := some "Demonstrate an average operating profit of at least fifteen crore rupees, calculated on a restated and consolidated basis, during the preceding three years (of twelve months each), with operating profit in each of these preceding three years." },
  { id := "ICDR_6_1_c", title := "Net worth ≥ ₹1 cr in each of last 3 years", reference := "Regulation 6(1)(c)", check := fun i => (i.net_worths.length == 3) && i.net_worths.all (fun x => x >= 1000000), failReason := fun i => if (i.net_worths.length != 3) then "Need 3 full-year net worth figures." else "Net worth below ₹1 cr in one or more of the preceding three years.", remedy? := some "Ensure a net worth of at least one crore rupees in each of the preceding three full years (of twelve months each), calculated on a restated and consolidated basis." },
  { id := "ICDR_7_1_a", title := "Application for in-principle approval", reference := "Regulation 7(1)(a)", check := fun i => i.applied_to_stock_exchange, failReason := fun _ => "No application for in-principle approval from stock exchange(s) found." },
  { id := "ICDR_7_1_b", title := "Agreement with depository for dematerialisation", reference := "Regulation 7(1)(b)", check := fun i => i.has_demat_agreement, failReason := fun _ => "No agreement with depository for dematerialisation of specified securities found." },

{ id := "rule_7_1_c", title := "Dematerialised form of promoter's securities", reference := "Regulation 7(1)(c)", maps_to := [ { field := "promoter_securities_demat" } ], check := fun i => i.promoter_securities_demat, failReason := fun _ => "Promoters' specified securities not in dematerialised form." },
  { id := "rule_7_1_d", title := "Fully paid-up equity shares or forfeiture", reference := "Regulation 7(1)(d)", maps_to := [ { field := "fully_paid_up_equity_shares" } ], check := fun i => i.no_partly_paid_shares, failReason := fun _ => "Existing partly paid-up equity shares not fully paid-up or forfeited." },
  { id := "rule_7_1_e", title := "Firm arrangements of finance", reference := "General conditions", maps_to := [ { field := "finance_arrangements", type_hint := "OptionListNat" } ], check := fun i => i.finance_75_percent_done, failReason := fun _ => "No firm arrangements of finance for 75% of the project's funding." },
  { id := "rule_8", title := "Minimum holding period for equity shares offered for sale", reference := "Regulation 8", maps_to := [ { field := "min_holding_period", type_hint := "Nat" } ], check := fun i => i.shares_held_duration_months >= 12, failReason := fun _ => "Equity shares offered for sale not held for at least one year." },
  { id := "rule_8_1", title := "Holding period for convertible securities and resulting equity shares", reference := "ICDR_8_1", maps_to := [ { field := "convertible_securities", type_hint := "List Nat" } ], check := fun i => i.underlying_held_1y, failReason := fun _ => "Convertible securities and resulting equity shares not held for at least one year." },

{ id := "ICDR_6_8_provided", title := "Max sale of equity shares for unidentified targets", reference := "Regulation 6(8)",
    check := fun i => i.max_sale_unidentified_targets <= 25,
    failReason := fun i => "The maximum sale of equity shares for unidentified acquisition or investment targets exceeds 25%.",
    remedy? := some "Limit the amount raised for such objects to not more than 25%." },
  { id := "ICDR_6_8_provided_further", title := "Exceptions to max sale of equity shares", reference := "Regulation 6(8)",
    check := fun _ => True, -- No clear condition in the text; a conservative predicate is used.
    failReason := fun _ => "The proposed acquisition or strategic investment object has not been identified and suitable specific disclosures have not been made." },
  { id := "ICDR_8_provided_further", title := "Additional conditions for conversion of compulsorily convertible securities", reference := "Regulation 8",
    check := fun i => i.convertibles_not_issued_from_revaluation && i.convertibles_not_issued_from_unrealized_profits,
    failReason := fun i => if i.convertibles_issued_from_revaluation then "Convertible securities are issued by utilization of revaluation reserves." else if i.convertibles_issued_from_unrealized_profits then "Convertible securities are issued by utilization of unrealized profits." else "Not applicable.",
    remedy? := some "Ensure that convertible securities are not issued out of revaluation reserves or unrealized profits." },
  { id := "ICDR_9", title := "Issuer may issue CDI without prior equity IPO", reference := "Regulation 9",
    check := fun i => !i.default_of_payment,
    failReason := fun i => "The issuer is in default of payment of interest or repayment of principal amount in respect of debt instruments issued by it to the public for a period of more than six months." },
  { id := "ICDR_10_1a", title := "Credit rating required for CDI offer", reference := "Regulation 10(1)(a)",
    check := fun i => i.credit_rating_obtained,
    failReason := fun i => "The issuer has not obtained credit rating from at least one credit rating agency." },

{ id := "ICDR_9_6", title := "Default payment of interest or repayment of principal", reference := "Regulation 9",
    check := fun i => i.default_payment_status.isSome,
    failReason := fun _ => "Issuer is in default of payment of interest or repayment of principal amount for a period of more than six months.", remedy? := none },
  { id := "ICDR_10_a", title := "Credit rating and debenture trustee requirements", reference := "Regulation 10(1)(a)",
    check := fun i => i.credit_rating.isSome && i.debenture_trustee.length > 0,
    failReason := fun _ => "Issuer has not obtained credit rating from at least one credit rating agency or has not appointed a debenture trustee.", remedy? := some "Obtain credit rating and appoint a debenture trustee." },
  { id := "ICDR_10_c", title := "Debenture redemption reserve", reference := "Regulation 10(1)(c)",
    check := fun i => i.debenture_redemption_reserve.isSome,
    failReason := fun _ => "Issuer has not created a debenture redemption reserve in accordance with the provisions of the Companies Act, 2013 and rules made thereunder." },
  { id := "ICDR_11_1", title := "Consent for conversion of convertible debt instruments", reference := "Regulation 11(1)",
    check := fun i => i.consent_for_conversion,
    failReason := fun _ => "Issuer has not obtained positive consent from holders for the conversion of optionally convertible debt instruments into equity shares." },
  { id := "ICDR_11_2", title := "Option to not convert convertible portion into equity shares", reference := "Regulation 11(2)",
    check := fun i => (i.option_not_convert.isDefined) & (i.net_worths.last > 100000000),
    failReason := fun _ => "The value of the convertible portion of any listed convertible debt instruments issued by an issuer exceeds ten crore rupees, and the issuer has determined the conversion price but holders have not been given the option to not convert." },

{ id := "rule_13_a", title := "Warrant tenure ≤ 18 months", reference := "Regulation 13(a)",
    check := fun i => i.warrant_tenure <= 18 * 12,
    failReason := fun i => "Warrant tenure exceeds 18 months.",
    remedy? := some "Adjust warrant tenure to be less than or equal to 18 months." },
  { id := "rule_13_c", title := "Warrant exercise price formula and upfront payment", reference := "Regulation 13(c)",
    check := fun i => i.warrant_exercise_price.isSome && i.upfront_payment > (25 / 100) * i.warrant_exercise_price.get,
    failReason := fun i => if i.warrant_exercise_price.isNone then "Warrant exercise price not provided." else "Upfront payment less than 25% of the exercise price.",
    remedy? := some "Provide a formula for determining the exercise price and ensure at least 25% of the consideration amount based on the exercise price is received upfront." },
  { id := "rule_13_d", title := "Forfeiture of consideration for un-exercised warrants", reference := "Regulation 13(d)",
    check := fun i => i.warrant_tenure <= 3 * 12 && (i.warrant_exercise_price.isSome || i.upfront_payment == 0),
    failReason := fun i => if i.warrant_tenure > 3 * 12 then "Warrant tenure exceeds 3 months." else "No warrant exercise price or upfront payment provided.",
    remedy? := some "Ensure the warrant tenure is less than or equal to 3 months and provide a warrant exercise price and upfront payment." },
  { id := "rule_14_1", title := "Minimum promoters’ contribution ≥ 20%", reference := "Regulation 14(1)",
    check := fun i => i.promoter_contribution >= 20,
    failReason := fun i => "Promoters' contribution is less than 20%.",
    remedy? := some "Increase promoters' contribution to at least 20% of the post-issue capital." },
  { id := "rule_14_1_a", title := "Promoter contribution by equity shares or convertible securities", reference := "Regulation 14(1)",
    check := fun i => i.contribution_method.isSome,
    failReason := fun i => "Contribution method not provided.",
    remedy? := some "Specify whether the promoter contribution is made by equity shares or convertible securities." },

{ id := "ICDR_14_1_b", title := "Undisclosed conversion price", reference := "Regulation 14(1)", check := fun i => not (i.operating_profits.exists (fun x => x.length > 0) && i.promoter_securities_demat), failReason := "Promoters have not disclosed the conversion price or have no operating profits." },
  { id := "ICDR_6_3", title := "Promoters' contribution computation", reference := "ICDR_6_3", check := fun _ => True, failReason := "The rule requires complex computations that cannot be represented in the provided Issuer structure." },
  { id := "ICDR_6_4", title := "Securities ineligible for minimum promoters’ contribution", reference := "ICDR_6_4", check := fun i => i.securities_ineligible.isEmpty, failReason := "The Issuer does not have any securities ineligible for minimum promoters' contribution." },
  { id := "ICDR_12_a", title := "Promoters’ contribution computation", reference := "ICDR_12_a", check := fun _ => True, failReason := "The rule requires complex computations that cannot be represented in the provided Issuer structure." },
  { id := "ICDR_12_a_ii", title := "Exercise of employee stock options or SARs", reference := "ICDR_12_a_ii", check := fun _ => True, failReason := "The rule requires complex computations that cannot be represented in the provided Issuer structure." },

{ id := "rule_4_13_a", title := "Payment for specified securities acquired by promoters", reference := "Regulation 4(1)(a)", check := fun i => i.specified_securities.all (fun x => i.has_paid_for_promoter_securities x), failReason := fun i => "No payment for specified securities acquired by promoters.", remedy? := none },
  { id := "rule_4_13_b", title := "Payment for specified securities acquired under Companies Act", reference := "Regulation 4(1)(b)", check := fun i => i.specified_securities.all (fun x => i.payment_for_companies_act_securities x), failReason := fun i => "No payment for specified securities acquired under Companies Act.", remedy? := none },
  { id := "rule_4_13_c", title := "Payment for specified securities in government company IPO", reference := "Regulation 4(1)(c)", check := fun i => i.specified_securities.all (fun x => i.payment_for_govt_company_ipo x), failReason := fun i => "No payment for specified securities in government company IPO.", remedy? := none },
  { id := "rule_4_13_d", title := "Specified securities allotted to promoters at a price less than issue price", reference := "Regulation 4(1)(d)", check := fun i => i.specified_securities.all (fun x => i.lower_price_for_promoter_securities x), failReason := fun i => "Specified securities allotted to promoters at a price greater than issue price.", remedy? := none },
  { id := "rule_16_1", title := "Lock-in of specified securities held by the promoters", reference := "ICDR_16_1", check := fun i => i.securities_held_by_promoters.map (fun x => i.lock_in_for_promoter_securities x), failReason := fun i => "No lock-in for specified securities held by promoters.", remedy? := none },

{ id := "ICDR_16_49a", title := "Promoter lock-in period (initial offer)", reference := "Regulation 16(49)", check := fun i => i.lock_in_period == some 180 or (i.lock_in_period == none && i.issue_proceeds_capital_expenditure), failReason := fun i => if i.lock_in_period != some 180 then "Promoter lock-in period should be 18 months." else if i.lock_in_period != none && not i.issue_proceeds_capital_expenditure then "Lock-in period for promoters should be 3 years if majority of issue proceeds is for capital expenditure.", remedy? := some "Adjust lock-in period to comply with ICDR." },
  { id := "ICDR_16_49b", title := "Promoter excess holding lock-in (initial offer)", reference := "Regulation 16(49)", check := fun i => i.lock_in_period == some 180 or (i.lock_in_period == none && i.issue_proceeds_capital_expenditure), failReason := fun i => if i.lock_in_period != some 180 then "Promoter excess holding lock-in period should be 6 months." else if i.lock_in_period != none && not i.issue_proceeds_capital_expenditure then "Lock-in period for promoter excess holding should be 1 year if majority of issue proceeds is for capital expenditure.", remedy? := some "Adjust lock-in period to comply with ICDR." },
  { id := "ICDR_17", title := "Non-promoter lock-in (initial offer)", reference := "ICDR_17", check := fun i => i.lock_in_period > 0, failReason := fun i => "Lock-in period for equity shares held by persons other than promoters should be greater than zero." },
  { id := "ICDR_17_a", title := "Exceptions to lock-in (employees and employee stock option trusts)", reference := "ICDR_17_a", check := fun _ => True, failReason := "This rule does not apply to equity shares allotted to employees or held by an employee stock option trust." },
  { id := "ICDR_17_c", title := "Lock-in for venture capital funds (initial offer)", reference := "ICDR_17_c", check := fun i => i.lock_in_period > 0, failReason := fun i => "Lock-in period for equity shares held by a venture capital fund or alternative investment fund should be greater than zero." },

{ id := "ICDR_21_a", title := "Pledge of locked-in specified securities (a)", reference := "Regulation 21(a)", check := fun i => i.locked_in_securities.length > 0 && i.locked_in_securities.all (fun x => x == 1) && i.is_loan_granted_to_issuer, failReason := fun i => if not (i.locked_in_securities.length > 0) then "Specified securities not locked-in." else if not (i.locked_in_securities.all (fun x => x == 1)) then "Only one specified security can be locked-in." else if not i.is_loan_granted_to_issuer then "Loan granted to issuer company is required." },
  { id := "ICDR_21_b", title := "Pledge of locked-in specified securities (b)", reference := "Regulation 21(b)", check := fun i => i.locked_in_securities.length > 0 && i.locked_in_securities.all (fun x => x == 1) && i.is_loan_terms, failReason := fun i => if not (i.locked_in_securities.length > 0) then "Specified securities not locked-in." else if not (i.locked_in_securities.all (fun x => x == 1)) then "Only one specified security can be locked-in." else "Pledge of specified securities is not one of the loan terms." },
  { id := "ICDR_21", title := "Pledge of locked-in specified securities", reference := "Regulation 21", check := fun i => i.locked_in_securities.length > 0 && i.locked_in_securities.all (fun x => x == 1) && not i.is_sr_equity_shares, failReason := fun i => if not (i.locked_in_securities.length > 0) then "Specified securities not locked-in." else if not (i.locked_in_securities.all (fun x => x == 1)) then "Only one specified security can be locked-in." else "SR equity shares are excluded from pledge." },
  { id := "ICDR_22", title := "Transfer of locked-in specified securities", reference := "ICDR_22", check := fun _ => True, failReason := "Regulation 22 does not provide a machine-checkable compliance rule. Please consult the text for details." },
  { id := "ICDR_23", title := "Rights, obligations and responsibilities of lead managers", reference := "ICDR_23", check := fun i => Option.some (i.lead_manager_roles).map (fun lmrs => lmrs.all (fun r => List.mem r i.lead_manager_roles)), failReason := fun i => if i.lead_manager_roles == none then "No lead managers specified." else "Lead manager roles not predetermined and disclosed." }
]

def issuerQuestions : List (String × String × String) := [
("net_tangible_assets", "What is the net tangible assets for each of the last three years?", "List Nat"),
  ("operating_profits", "What are the operating profits for each of the last three years?", "List Nat"),
  ("net_worths", "What is the net worth for each of the last three years?", "List Nat"),
("promoter_securities_demat", "Is the dematerialised form of promoter's securities available?", "Bool"),
  ("no_partly_paid_shares", "Are there any partly paid-up equity shares?", "Bool"),
  ("finance_arrangements", "What are the firm arrangements of finance for the project?", "OptionListNat"),
  ("min_holding_period", "How long have the equity shares been held before offering them for sale?", "Nat"),
  ("convertible_securities", "What is the holding period for convertible securities and resulting equity shares?", "List Nat"),
{ "max_sale_unidentified_targets", "What percentage of the amount being raised by the issuer can be used for unidentified acquisition or investment targets?", "Nat" },
  { "convertibles_not_issued_from_revaluation", "Are convertible securities issued out of revaluation reserves?", "Bool" },
  { "convertibles_not_issued_from_unrealized_profits", "Are convertible securities issued by utilization of unrealized profits of the issuer?", "Bool" },
  { "default_of_payment", "Is the issuer in default of payment of interest or repayment of principal amount in respect of debt instruments issued by it to the public for a period of more than six months?", "Bool" },
  { "credit_rating_obtained", "Has the issuer obtained credit rating from at least one credit rating agency?" , "Bool" },
("default_payment_status", "Has the issuer defaulted on payment of interest or repayment of principal?", "OptionBool"),
  ("credit_rating", "Has the issuer obtained credit rating from at least one credit rating agency?", "OptionBool"),
  ("debenture_trustee", "Who are the debenture trustees appointed by the issuer?", "List Nat"),
  ("debenture_redemption_reserve", "Has the issuer created a debenture redemption reserve?", "OptionBool"),
  ("consent_for_conversion", "Has the issuer obtained positive consent from holders for the conversion of optionally convertible debt instruments into equity shares?", "Bool"),
  ("option_not_convert", "Should holders of listed convertible debt instruments be given the option to not convert the convertible portion into equity shares?", "OptionBool"),
{ "warrant_tenure", "What is the tenure of the warrants in months?", "Nat" },
  { "warrant_exercise_price", "What is the price or formula for determining the exercise price of the warrants?", "OptionString" },
  { "upfront_payment", "What percentage of the consideration amount based on the exercise price is received upfront?", "Nat" },
  { "promoter_contribution", "What percentage of the post-issue capital do the promoters hold?", "Nat" },
  { "contribution_method", "How does the promoter contribute (equity shares or convertible securities)?", "OptionString" },
("promoter_securities_demat", "Have promoters disclosed their securities?", "Bool"),
  ("securities_ineligible", "Which securities are ineligible for minimum promoters’ contribution?", "List Nat"),
{ "specified_securities", "Which securities are subject to this rule?", "List Nat" },
  { "has_paid_for_promoter_securities", "Has payment been made for the specified securities acquired by promoters?", "Bool" },
  { "payment_for_companies_act_securities", "Has payment been made for the specified securities acquired under Companies Act?", "Bool" },
  { "payment_for_govt_company_ipo", "Has payment been made for the specified securities in government company IPO?", "Bool" },
  { "lower_price_for_promoter_securities", "Were the specified securities allotted to promoters at a price less than issue price?", "Bool" },
  { "lock_in_for_promoter_securities", "Are the specified securities held by promoters subject to lock-in?", "Option Bool" },
{ "lock_in_period", "What is the lock-in period for promoters' contribution?", "OptionNat" },
  { "lock_in_period", "What is the lock-in period for promoter excess holding?", "OptionNat" },
  { "lock_in_period", "What is the lock-in period for equity shares held by persons other than promoters?", "Nat" },
{ "locked_in_securities", "How many locked-in specified securities?", "List Nat" },
  { "is_loan_granted_to_issuer", "Was the loan granted to the issuer company or its subsidiary(ies) for the purpose of financing one or more of the objects of the issue?", "Bool" },
  { "is_sr_equity_shares", "Are the specified securities SR equity shares?", "Bool" },
  { "lead_manager_roles", "What are the predetermined roles, obligations and responsibilities of each lead manager?", "OptionListNat" }
]

end GeneratedRules
